### ISSUE TITLE
Icons can't be used inside links

### ISSUE THREAD

**Issue by atnbueno** [ComboStrap/dokuwiki-template-strap#5] opened 2021-03-06 22:36 UTC
This code:
```
[[goup|<icon name="arrow-top-bold-circle" /> Go Up!]]
```
doesn't render the icon. Is there another syntax compatible with icons in links?

**Comment by gerardnico** [comment] 2021-03-07 14:23
Yes that's true. This is because the dokuwiki syntax allows only media in its content.
The icon are also SVG and they are by default disabled in dokuwiki for security reasons. 

We takes over the links inside the combo component. May be we can take over the links entirely and allows other syntaxes in the body of a link. 

There is also other side effect such as baclinks and page move that should be taken account.

For a quick solution, if you allows SVG as media, you can insert it as media in the link.

**Comment by gerardnico** [comment] 2021-03-09 15:57
I took over the link implementation of dokuwiki.

This is a big component in a web site.
The email links, the internal links, the interwiki links, the external links, the rewrite of links (caused by a page move), the backlinks creation (the index) and the default name of the links have been tested. 

Check the results:

https://combostrap.com/ui/link#icon

Is this what you wanted ?

Cheers
Nico

**Comment by atnbueno** [comment] 2021-03-09 18:38
Bravo! 👏🏼👏🏼

**Comment by gerardnico** [comment] 2021-03-09 18:41
Thanks. I will closed it after the release.

**Comment by gerardnico** [comment] 2021-03-19 20:01
Same comment ...

The new version has been released.
https://combostrap.com/changes#version_112_-_2021-03-19

The new release is tested actually on key clients for a couple of days.
You can test it or wait that I publish the date on dokuwiki (The build has passed)

Nice weekend

**Closed as completed by gerardnico** 2021-03-19 20:01 UTC
Labels: enhancement
